version: "3"
services: 
    node-app:
        build: .
        ports: 
            - "3000:3000"
        environment:  
            - PORT=3000
        depends_on: 
            - mongo
    
    mongo:
        image: mongo
        restart: always
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=shambhu
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes: 
            - mongo-db:/data/db

    redis:
        image: redis
    
volumes: 
    mongo-db: