version: "3"
services: 
    node-app:
        build: 
            context: .
            args: 
                NODE_ENV: development
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development 
            - MONGO_USER=shambhu
            - MONGO_PASSWORD=root
        command: npm run dev
    mongo:
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=shambhu
            - MONGO_INITDB_ROOT_PASSWORD=root     